name: Lint

on: [push]

jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2  # Checkout code

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.18.1'  # Specify your Node.js version

      - name: Install dependencies
        run: |
          npm install  # Install dependencies, including ESLint

      - name: Run ESLint
        run: |
          npx eslint --fix  # Run ESLint directly via npx 